# specify the node base image with your desired version node:<version>
FROM node:18
# replace this with your application's default port
EXPOSE 3000
# Set the working directory in the container
WORKDIR /app

# Copy the application files into the working directory
COPY . /app

# Install the application dependencies
RUN npm install

# Define the entry point for the container
CMD ["npm", "start"]